### Temporal analysis

In [15]:
from src.temporal import *
from src.config import ROOT

In [16]:
wide, changes, rankings = temporal_analysis(
    ROOT / "data" / "results" / "csv" / "district_statistics.csv",
    ROOT / "data" / "results" / "csv",
)

Checks:

In [3]:
wide

        district  year      NDBI      NDVI      NDWI
0       DEHRADUN  2016 -0.167543  0.519588 -0.392459
1       DEHRADUN  2022 -0.249470  0.556234 -0.423061
2       DEHRADUN  2025 -0.171657  0.427429 -0.303357
3       HARIDWAR  2016 -0.143946  0.448835 -0.337198
4       HARIDWAR  2022 -0.181892  0.480971 -0.367786
5       HARIDWAR  2025 -0.114200  0.368553 -0.254582
6  PAURI GARHWAL  2016 -0.194869  0.539146 -0.404772
7  PAURI GARHWAL  2022 -0.243455  0.533821 -0.399632
8  PAURI GARHWAL  2025 -0.214963  0.459904 -0.322974

In [4]:
changes

,district,NDVI_2016,NDVI_2022,NDVI_2025,NDVI_change_16_22,NDVI_change_22_25,NDVI_change_16_25,NDWI_2016,NDWI_2022,NDWI_2025,NDWI_change_16_22,NDWI_change_22_25,NDWI_change_16_25,NDBI_2016,NDBI_2022,NDBI_2025,NDBI_change_16_22,NDBI_change_22_25,NDBI_change_16_25,NDVI_pct_change
0,DEHRADUN,0.519588,0.556234,0.427429,0.036646,-0.128805,-0.092159,-0.392459,-0.423061,-0.303357,-0.030602,0.119704,0.089102,-0.167543,-0.249470,-0.171657,-0.081927,0.077813,-0.004114,-17.736943
1,HARIDWAR,0.448835,0.480971,0.368553,0.032135,-0.112418,-0.080282,-0.337198,-0.367786,-0.254582,-0.030588,0.113205,0.082616,-0.143946,-0.181892,-0.114200,-0.037946,0.067692,0.029746,-17.886783
2,PAURI GARHWAL,0.539146,0.533821,0.459904,-0.005325,-0.073917,-0.079241,-0.404772,-0.399632,-0.322974,0.005140,0.076658,0.081798,-0.194869,-0.243455,-0.214963,-0.048586,0.028492,-0.020094,-14.697579

In [14]:
rankings["ndwi_increase"]

,district,NDVI_2016,NDVI_2022,NDVI_2025,NDVI_change_16_22,NDVI_change_22_25,NDVI_change_16_25,NDWI_2016,NDWI_2022,NDWI_2025,NDWI_change_16_22,NDWI_change_22_25,NDWI_change_16_25,NDBI_2016,NDBI_2022,NDBI_2025,NDBI_change_16_22,NDBI_change_22_25,NDBI_change_16_25,NDVI_pct_change
0,DEHRADUN,0.519588,0.556234,0.427429,0.036646,-0.128805,-0.092159,-0.392459,-0.423061,-0.303357,-0.030602,0.119704,0.089102,-0.167543,-0.249470,-0.171657,-0.081927,0.077813,-0.004114,-17.736943
1,HARIDWAR,0.448835,0.480971,0.368553,0.032135,-0.112418,-0.080282,-0.337198,-0.367786,-0.254582,-0.030588,0.113205,0.082616,-0.143946,-0.181892,-0.114200,-0.037946,0.067692,0.029746,-17.886783
2,PAURI GARHWAL,0.539146,0.533821,0.459904,-0.005325,-0.073917,-0.079241,-0.404772,-0.399632,-0.322974,0.005140,0.076658,0.081798,-0.194869,-0.243455,-0.214963,-0.048586,0.028492,-0.020094,-14.697579