In [11]:
from src.config import ROOT
from src.auxiliary_data import *

In [12]:
Raw_Census = ROOT / "data" / "raw" / "census"
Raw_HMIS = ROOT / "data" / "raw" / "hmis"
OUT = ROOT / "data" / "processed"
OUT.mkdir(parents=True, exist_ok=True)

### Extract desired data from PCA data, India & States/UTs - State and district level - 2011

In [13]:
Files_Census = {
    "Dehradun": Raw_Census / "DDW_PCA0000_2011_Indiastatedist.xlsx",
    "Haridwar": Raw_Census / "DDW_PCA0000_2011_Indiastatedist.xlsx",
    "Pauri Garhwal": Raw_Census / "DDW_PCA0000_2011_Indiastatedist.xlsx",
}

Keep_Census = [
    "Name",
    "TRU",
    "TOT_P",
    "No_HH",
    "P_LIT",
    "P_ILL",
    "TOT_WORK_P",
    "NON_WORK_P",
    "P_06",
    "P_SC",
    "P_ST",
]

In [14]:
get_dist_totals(Files_Census, Keep_Census, OUT)

        District  Population  Households  Literates  Illiterates  Workers  \
0       Dehradun     1696694      347001    1259506       437188   582768
1       Haridwar     1890422      338104    1178354       712068   578121
2  Pauri Garhwal      687271      161778     494889       192382   274152

   NonWorkers  Children_0_6  SC_Population  ST_Population  LiteracyRate  \
0     1113926        201652         228901         111663         74.23
1     1312301        285693         411274           6323         62.33
2      413119         83901         122361           2215         72.01

   WorkerRate  ChildRate  SC_Rate  ST_Rate
0       34.35      11.88    13.49     6.58
1       30.58      15.11    21.76     0.33
2       39.89      12.21    17.80     0.32

,District,Population,Households,Literates,Illiterates,Workers,NonWorkers,Children_0_6,SC_Population,ST_Population,LiteracyRate,WorkerRate,ChildRate,SC_Rate,ST_Rate
0,Dehradun,1696694,347001,1259506,437188,582768,1113926,201652,228901,111663,74.23,34.35,11.88,13.49,6.58
1,Haridwar,1890422,338104,1178354,712068,578121,1312301,285693,411274,6323,62.33,30.58,15.11,21.76,0.33
2,Pauri Garhwal,687271,161778,494889,192382,274152,413119,83901,122361,2215,72.01,39.89,12.21,17.80,0.32

In [ ]:
Files_HIMS = {
    "Dehradun": Raw_HMIS / "Dehradun.xlsx",
    "Haridwar": Raw_HMIS / "Haridwar.xlsx",
    "Pauri Garhwal": Raw_HMIS / "PauriGarhwal.xlsx",
}

Keep_HMIS = {
    # Maternal Health
    "Total number of pregnant women registered for ANC":
        "ANC_Registered",

    "Number of Institutional Deliveries conducted (Including C-Sections)":
        "Institutional_Deliveries",

    "Total C -Section deliveries performed":
        "CSection_Deliveries",

    # Child Health
    "Children aged between 9 and 11 months fully immunized- Male":
        "Fully_Immunized_Male",

    "Children aged between 9 and 11 months fully immunized - Female":
        "Fully_Immunized_Female",

    "Number of newborns having weight less than 2.5 kg":
        "Low_Birth_Weight",

    "Childhood Diseases - Severe Acute Malnutrition (SAM)":
        "SAM",

    # Communicable Diseases
    "Childhood Diseases - Malaria":
        "Malaria",

    "Dengue - Enzyme- Linked Immuno Sorbent Assay (ELISA) Test Positive":
        "Dengue",

    "Childhood Diseases - Tuberculosis (TB)":
        "Tuberculosis",

    "Childhood Diseases - Diarrhoea":
        "Diarrhoea",

    # Health Service Utilization
    "Allopathic- Outpatient attendance":
        "OPD",

    "In-Patient Head Count at midnight":
        "Inpatients",

    "Number of Lab Tests done":
        "Lab_Tests",
}

In [16]:
get_hmis_data(Files_HIMS, Keep_HMIS, OUT)

/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/.venv/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/.venv/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/.venv/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

        District  ANC_Registered Institutional_Deliveries  \
0       Dehradun            5204                     None
1       Haridwar            7114                     None
2  Pauri Garhwal            1453                     None

   CSection_Deliveries Fully_Immunized_Male  Fully_Immunized_Female  \
0                 1136                 None                    2066
1                  688                 None                    2300
2                  321                 None                     650

   Low_Birth_Weight   SAM  Malaria Dengue Tuberculosis  Diarrhoea     OPD  \
0               561  None        0   None         None        412  209970
1               648  None        2   None         None        154  169067
2               114  None        0   None         None        166  102637

   Inpatients  Lab_Tests
0        7925     117905
1        2676      55544
2        5461      64770

/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]
/Users/abhaypratap/OneHealth-Env-Monitoring-Uttarakhand/src/auxiliary_data.py:73: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[2]

,District,ANC_Registered,Institutional_Deliveries,CSection_Deliveries,Fully_Immunized_Male,Fully_Immunized_Female,Low_Birth_Weight,SAM,Malaria,Dengue,Tuberculosis,Diarrhoea,OPD,Inpatients,Lab_Tests
0,Dehradun,5204,None,1136,None,2066,561,None,0,None,None,412,209970,7925,117905
1,Haridwar,7114,None,688,None,2300,648,None,2,None,None,154,169067,2676,55544
2,Pauri Garhwal,1453,None,321,None,650,114,None,0,None,None,166,102637,5461,64770